flowchart TD
    Init([Rough Learning Goal & Personal Context]) --> KB{Known Content?}

    %% Knowledge Base Building
    KB -->|No or Partial| Search[Search and Curate Content]
    Search --> KBReady

    KB -->|Yes| Upload[Upload your material]
    Upload --> KBReady

    KBReady[Knowledge Base Ready]

    %% Optional Exploration
    KBReady --> Explore{80/20 Exploration?}
    Explore -.->|Yes| Insights[Top 5 Insights & Surprises]
    Insights -.-> Notes
    Insights -.-> Assessment

    Explore -->|No| Assessment[Self-Assessment Questions]
    Assessment -.-> Notes

    %% Self Assessment
    Assessment --> AssSum[Summary of Gaps & Strengths]
    AssSum --> DefineL[Fine-tune Learning Goals]

    %% Socratic Learning
    DefineL --> LearningPath[Create Learning Path]
    LearningPath --> Session[Go through 4Cs Sessions: Connection, Concept, Concrete Practice, Conclusion]

    %% Optional Tracking
    Session -.-> Notes([Optional: Notes and Flashcards])
    
    %% Styling for optional blocks
    classDef optional fill:#f9f9f9,stroke:#333,stroke-dasharray: 5 5,stroke-width:2px;
    class Insights,Refine2,Flashcards,Notes,Practice,Deepen optional;
